name: sih
description: A Flutter project for SIH 2022.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  connection_notifier: ^0.0.1
  cupertino_icons: ^1.0.2
  dio: null
  dropdown_search: ^5.0.2
  file_picker: ^5.0.1
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  geocoding: ^2.0.4
  geolocator: ^9.0.1
  lottie: ^1.4.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/data/
    - assets/images/
